### PR TITLE
Keys: Update default.can_interact_with_node to new item meta

### LINKED ISSUE #1626: Right clicking with assigned key on locked chest crash
Continuation of https://github.com/minetest/minetest_game/issues/1625

Since I've assigned my new key to locked chest I tried to use it on said locked chest by right clicking and got this error:
```
2017-03-12 14:35:16: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod '' in callback item_OnPlace(): ...st\bin\..\games\minetest_game\mods\default/functions.lua:559: attempt to index local 'key_meta' (a nil value)
2017-03-12 14:35:16: ERROR[Main]: stack traceback:
2017-03-12 14:35:16: ERROR[Main]: 	...st\bin\..\games\minetest_game\mods\default/functions.lua:559: in function 'can_interact_with_node'
2017-03-12 14:35:16: ERROR[Main]: 	...netest\bin\..\games\minetest_game\mods\default/nodes.lua:1787: in function 'on_rightclick'
2017-03-12 14:35:16: ERROR[Main]: 	...netest\bin\..\games\minetest_game\mods\default/tools.lua:444: in function <...netest\bin\..\games\minetest_game\mods\default/tools.lua:438>
```

Same error for trying to use this key on different chest.

### PR DESCRIPTION
**Pull request by SmallJoker**
Completes a forgotten update in 9d3a526
Fixes #1626 and allows owner to access their nodes to any time, no matter what they're holding.

### CODE REVIEW

File: mods/default/functions.lua [hunk 1]
```diff
@@ -554,13 +554,16 @@ function default.can_interact_with_node(player, pos)
...
+		local key_meta = item:get_meta()
 		local secret = meta:get_string("key_lock_secret")
-		if secret ~= key_meta.secret then
-			return false
+
+		if key_meta:get_string("secret") == "" then
+			key_meta:set_string("secret", minetest.parse_json(item:get_metadata()).secret)
 		end
 
-		return true
```
Comment (SmallJoker) [inline mods/default/functions.lua]: Note to reviewers: This line was removed to allow owners to access the node at any time - no matter what item is being hold

**Comment by Fixer-007** [comment]
Fixed the problem for me.

File: mods/default/functions.lua [hunk 2]
```diff
@@ -551,21 +551,23 @@ function default.can_interact_with_node(player, pos)
...
+		local key_meta = item:get_meta()
 		local secret = meta:get_string("key_lock_secret")
-		if secret ~= key_meta.secret then
-			return false
-		end
 
-		return true
-	end
+		if key_meta:get_string("secret") == "" then
+			key_meta:set_string("secret", minetest.parse_json(item:get_metadata()).secret)
```
Comment (rubenwardy) [inline mods/default/functions.lua]: set_metadata("")

File: mods/default/functions.lua [hunk 3]
```diff
@@ -551,21 +551,23 @@ function default.can_interact_with_node(player, pos)
...
+		end
 
-	if player:get_player_name() ~= meta:get_string("owner") then
-		return false
+		return secret == key_meta:get_string("secret")
```
Comment (rubenwardy) [inline mods/default/functions.lua]: I suggest moving `local secret` above here, or doing

```lua
return meta:get_string("key_lock_secret") == key_meta:get_string("secret")
```

File: mods/default/functions.lua (hunk 2 above)
Comment (SmallJoker) [inline mods/default/functions.lua]: Added for the other places too.
