### PR TITLE
Fix bed night skip race condition

### LINKED ISSUE #3066: Spam-tapping on beds and more...
I thought that the bug I encountered was related to the "beds" mod (maybe it still is.)

https://github.com/minetest/minetest_game/assets/113429882/416645a3-9dec-437d-96b6-7c0fa3e679e8

Short description:
The current day was 92;
I spam-tapped on the bed to lie down and get up again and again;
After waking up and seeing "You can only sleep at night", the current day was 99.

==========

But then I remembered about a bug I found earlier.
I was spam-tapping under myself, swimming in lava. Somehow Sam has become invincible (although he can't interact with the world. (place blocks, execute commands etc.))

https://github.com/minetest/minetest_game/assets/113429882/4d5000e0-3609-43b0-af2a-625b37515cf7

https://github.com/minetest/minetest_game/assets/113429882/06f957c4-851c-43cc-b1e8-7f3fc5124760

Sorry for the low quality, GitHub doesn't allow files larger than 10MB.
Also, I don't fully understand how to replicate it. Sometimes it does, sometimes it doesn't.

If it helps, I was playing build 5.7.0 from F-Droid.

### PR DESCRIPTION
**Pull request by appgurueu**
Closes #3066 (partially, the other issue is an engine issue). How to test:

* Reproduce the bug. This is easiest if you introduce a `print` in `beds.skip_night`. Otherwise, don't spam click too fast, or the daytime won't have changed when the next set time of day hits, so the days counter will only be incremented by one. You have a whole 2 seconds to make your clicks, make about 3-4 clicks in that time (definitely don't make clicks with a < 100 ms (serverstep) frequency).
* Verify that the fix works.

### CODE REVIEW

File: mods/beds/functions.lua [hunk 1]
```diff
@@ -181,6 +181,25 @@ function beds.skip_night()
 	minetest.set_timeofday(0.23)
 end
 
+local update_scheduled = false
+local function schedule_update()
+	if update_scheduled then
+		-- there already is an update scheduled; don't schedule more to prevent races
+		return
+	end
+	update_scheduled = true
```
Comment (sfan5) [inline mods/beds/functions.lua:190]: this is never set to false?

Comment (appgurueu) [reply mods/beds/functions.lua:190]: oops, fixed
