### PR TITLE
Fix TNT explosions not removing metadata

### LINKED ISSUE #3179: explosions leave metadata behind
explosions remove all nodes without an `on_blast`-callback in VoxelManip. This leaves their metadata behind. 
I would expect they are removed. It's not good to have metadata in positions where nobody expects it...

### How to reproduce:
- place a `default:sign_wall_wood` and write some text on it
- create an explosion that will destroy the sign
- the flame at the sign position will now have an infotext and a formspec

### PR DESCRIPTION
**Pull request by appgurueu**
Fixes #3179. Check that:

1. Metadata of nodes that are blasted is correctly removed. Easiest way to test that is via the sign as described in the issue.
2. Metadata of nodes that aren't blasted is preserved. For example put something in a locked chest and check that it is still in there after the explosion.

### CODE REVIEW

File: mods/tnt/init.lua [hunk 1]
```diff
@@ -345,6 +345,14 @@ local function tnt_explode(pos, radius, ignore_protection, ignore_on_blast, owne
...
 	basic_flame_on_construct = minetest.registered_nodes["fire:basic_flame"].on_construct
 
+	-- Used to efficiently remove metadata of nodes that were destroyed.
+	-- Metadata is probably sparse, so this may save us some work.
+	local poses_with_meta = minetest.find_nodes_with_meta(p1, p2)
+	local has_meta = {}
+	for _, p in ipairs(poses_with_meta) do
+		has_meta[a:indexp(p)] = true
+	end
+
```
Comment (sfan5) [inline mods/tnt/init.lua:355]:
```suggestion
	local has_meta = {}
	for _, p in ipairs(minetest.find_nodes_with_meta(p1, p2)) do
		has_meta[a:indexp(p)] = true
	end

```

Comment (appgurueu) [reply mods/tnt/init.lua:355]: sure, why not. though i don't think it matters much.

**Review by sfan5 — APPROVED** [review]
lgmt, not tested
